### ISSUE TITLE
Can't attach via socket using Zsh

### ISSUE THREAD

**Issue by manufaktor** [ruby/vscode-rdbg#337] opened 2023-08-24 11:49 UTC
macOS: 13.1
rdbg 1.8.0
vscode: 1.81.1
vscode-rdbg: 0.2.1
zsh 5.8.1 (x86_64-apple-darwin22.0)

launch.json
```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "rdbg",
      "name": "Attach with rdbg",
      "request": "attach"
    }
  ]
}

```

Running Rails via Procfile.dev:
```
web: RUBY_DEBUG_OPEN=true bin/rails server -p 3000
```

## Problem description

When trying to attach in VSCode, I get this popup:

<img width="283" alt="Screenshot 2023-08-24 at 13 41 12" src="https://github.com/ruby/vscode-rdbg/assets/234051/4c08d039-0749-4af6-aa57-34c9128452a0">

I traced this back to `makeShellCommand`, which calls `/bin/zsh -lic 'rdbg --util=list-socks'`. This returns the following from stdout:

```
\u001b]7;file://immi.local/Users/immi/Code/denteo/dental\u0007/var/folders/dc/jyk9w7z52v13f5cb3ykj9x1c0000gn/T/ruby-debug-sock-501/ruby-debug-immi-47815
```

It looks like there is an escape sequence in there, which causes the successive code to not find the socket.

## Reproduction

I made this little script to reproduce, you can call it with `node test.js`

```
const util = require('node:util');
const exec = util.promisify(require('node:child_process').exec);

async function test() {
  const { stdout } = await exec("/bin/zsh -lic 'rdbg --util=list-socks'");
  console.log('stdout:', stdout);
  console.log('stdout json stringified:', JSON.stringify(stdout));
}
test();
```

This prints the following:

```
stdout: /var/folders/dc/jyk9w7z52v13f5cb3ykj9x1c0000gn/T/ruby-debug-sock-501/ruby-debug-immi-47815

stdout json stringified: "\u001b]7;file://immi.local/Users/immi/Code/denteo/dental\u0007/var/folders/dc/jyk9w7z52v13f5cb3ykj9x1c0000gn/T/ruby-debug-sock-501/ruby-debug-immi-47815\n"
```

In the stringified output you can see the escape sequence again. Is there a way to fix this?

Changing the `-lic` to `-c` on the zsh invocation gets rid of it, but I believe these flags have been introduced because of some rbenv issue (https://github.com/ruby/vscode-rdbg/commit/7e5eeb475efa4b7975bba39a8535374fcc611d73)

Any help is greatly appreciated.

Similar issues: #277 or #127

**Comment by vmcilwain** [comment] 2023-11-15 00:15
I am having this issue as well. Curious if there has been any progress or workaround?

**Comment by tridnguyen** [comment] 2023-11-15 00:20
> I am having this issue as well. Curious if there has been any progress or workaround?

The workaround I used was to downgrade to version `1.0` in VS Code.  You can do this from the uninstall dropdown: 
![image](https://github.com/ruby/vscode-rdbg/assets/1915197/816e9e41-fb59-4bdd-a920-47c978faa4d3)

**Comment by vmcilwain** [comment] 2023-11-15 01:05
Thank you. I just tried this and it worked. 
I really appreciate it.

**Comment by ono-max** [comment] 2023-12-26 04:40
Duplicate of https://github.com/ruby/vscode-rdbg/issues/277.

**Closed by ono-max** 2023-12-26 04:40 UTC
