### ISSUE TITLE
Attach mode does not work on version 0.2.1 using zsh

### ISSUE THREAD

**Issue by plfoley** [ruby/vscode-rdbg#277] opened 2023-06-02 21:01 UTC
When using zsh as the login shell, attaching to a running instance of Rails using UNIX Socket fails with the following error:
`connect ENOENT 1337;RemoteHost=<user>@<machine>.local 1337;CurrentDir=/Users/<user>/<repoDir> 1337;ShellIntegrationVersion=13;shell=zsh/var/folders/9v/<TempDir>/ruby-debug-sock-501/ruby-debug-<user>-7957`

macOS 13.4
VSCode 1.78.2
rdbg 1.7.1 & 1.8.0
Ruby 2.7.8
Rails 6.0.6

It work fine in version 0.1.0. It got broken in version 0.2.0

It is possible to attach to the process using TCP/IP but no breakpoint will be hit. It is however possible to break on exception when connected in this manner on version 0.2.1.

As reported in this [issue](https://github.com/ruby/vscode-rdbg/issues/250), there is no issue when using bash as the login shell on with version 0.2.1

**Comment by ono-max** [comment] 2023-06-03 12:53
Unfortunately, I'm not able to reproduce your error so far.

**Comment by ono-max** [comment] 2023-06-03 12:54
If you find a way to reproduce this problem, I'd appreciate it. Thank you.

**Comment by miharekar** [comment] 2023-06-03 14:15
Same issue here. Intel macOS, zsh, chruby 0.3.9, Ruby 3.2.2.

**Comment by ono-max** [comment] 2023-06-04 09:56
All right, let's use another approach.

**Comment by ono-max** [comment] 2023-06-04 09:59
@plfoley @miharekar 

Could you check the following steps?

```ruby
a=1
b=2
c=3
```

1. Run `$ rdbg target.rb --O`
2. Attaching to the debuggee (Attach with rdbg)

In my environment, I confirmed it works.

**Comment by miharekar** [comment] 2023-06-04 12:54
<img width="511" alt="CleanShot 2023-06-04 at 14 54 00" src="https://github.com/ruby/vscode-rdbg/assets/986645/44faaf18-ea6d-46d6-8a12-beadb364ac9c">

**Comment by plfoley** [comment] 2023-06-04 21:22
@ono-max I have the same issue as @miharekar.
Please make sure your login shell is set to zsh (macOS default)
`sudo chsh -s /bin/zsh`
You need to logoff-logon or restart to make it effective.

rdbg-vscode seems to ignore the terminal setting we set un VSCode and always use the Login Shell setting.

For example, If I change my Login Shell to bash:
`sudo chsh -s /bin/bash`
I can connect my debugger using version 0.2.1 as stated in Issue 250.

**Comment by ono-max** [comment] 2023-06-05 07:29
Thank you for reporting, but I was not able to reproduce the error 🤔 

I'm using the following environment:

* macOS Version 12.3.1
* zshell
* rdbg 1.8.0
* ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin21]

**Comment by ono-max** [comment] 2023-06-05 07:37
I've never seen this long error message. When attaching to the debuggee failed, I got the error message such as follows:
```
connect ECONNREFUSED 127.0.0.1:65373
```

**Comment by miharekar** [comment] 2023-06-05 08:16
Could it be an intel thing? I'm not on arm64 🤔 And I'm on macOS 13.4.

Also, if it helps narrowing down, I'm running [oh-my-zsh](https://ohmyz.sh/) with [powerlevel10k theme](https://github.com/romkatv/powerlevel10k).

Other than that our envs are the same.

**Comment by ono-max** [comment] 2023-06-05 08:36
Hmm, I confirmed it works with the following environment, too:

* ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin20]
* macOS Version 12.2

Thus, I don't think that it's related to OS.

**Comment by ono-max** [comment] 2023-06-05 08:39
@miharekar @plfoley 

Could you check the following steps?

1. Run `$ rdbg target.rb --O`
2. Run `$ rdbg --util=list-socks` in another window
I got the following results in my environment:
```shell
$ rdbg --util=list-socks
/var/folders/5j/z2c9zm7124q81f_py4xmd3scp7w9j7/T/ruby-debug-sock-746464807/ruby-debug-s15236-21955
```
3. Run `rdbg -A --sock-path=<socket path>`
I got the following results in my environment:
```shell
$ rdbg -A --sock-path=/var/folders/5j/z2c9zm7124q81f_py4xmd3scp7w9j7/T/ruby-debug-sock-746464807/ruby-debug-s15236-21955
/var/folders/5j/z2c9zm7124q81f_py4xmd3scp7w9j7/T/ruby-debug-sock-746464807/ruby-debug-s15236-21955
```

**Comment by miharekar** [comment] 2023-06-05 08:48
@ono-max yup, that seems to work just fine

```
❯ rdbg target.rb --O
DEBUGGER: Debugger can attach via UNIX domain socket (/var/folders/x1/h2b59yq14cs6pv9r_x1_39lw0000gn/T/ruby-debug-sock-501/ruby-debug-miharekar-10869)
DEBUGGER: wait for debugger connection...
DEBUGGER: Connected.
DEBUGGER: GreetingError: HEAD request
DEBUGGER: Disconnected.
DEBUGGER: Connected.
```

```
❯ rdbg --util=list-socks
/var/folders/x1/h2b59yq14cs6pv9r_x1_39lw0000gn/T/ruby-debug-sock-501/ruby-debug-miharekar-10869

   ~/Development/personal/rdbg                                                                                                          10:47:10
❯ rdbg -A --sock-path=/var/folders/x1/h2b59yq14cs6pv9r_x1_39lw0000gn/T/ruby-debug-sock-501/ruby-debug-miharekar-10869
DEBUGGER (client): Connected. PID:10869, $0:target.rb

[1, 3] in target.rb
=>   1| a=1
     2| b=2
     3| c=3
=>#0	<main> at target.rb:1
(rdbg:remote)
```

**Comment by st0012** [comment] 2023-06-05 08:48
Have you folks tried configuring the new [`"rdbg.rubyVersionManager"`](https://github.com/ruby/vscode-rdbg#selecting-a-version-manager) VS Code setting?

**Comment by ono-max** [comment] 2023-06-05 08:48
Thank you for your quick response!

**Comment by miharekar** [comment] 2023-06-05 08:55
@st0012 just now. Same result.

<img width="1133" alt="CleanShot 2023-06-05 at 10 51 15" src="https://github.com/ruby/vscode-rdbg/assets/986645/35bb3e4d-a569-4674-b80a-8f392969b068">


There is all of this in the VS Code output:
```
Error: Failed to activate Ruby environment using chruby. Error: Error: Command failed: /bin/zsh -lic 'chruby-exec "ruby-3.2" -- ruby' -rjson -e "printf(%{RUBY_ENV_ACTIVATE%sRUBY_ENV_ACTIVATE}, JSON.dump(ENV.to_h))"
(anon):setopt:7: can't change option: monitor

[[31mERROR[39m]: gitstatus failed to initialize.


  Add the following parameter to [4m~/.zshrc[24m for extra diagnostics on error:

    [1mGITSTATUS_LOG_LEVEL=DEBUG[0m

  Restart Zsh to retry gitstatus initialization:

    [32m[4mexec[24m[32m zsh[39m
zsh:1: command not found: chruby

Make sure to install rdbg command (`gem install debug`).
If you are using bundler, write `gem 'debug'` in your Gemfile.
(anon):setopt:7: can't change option: monitor


[[31mERROR[39m]: gitstatus failed to initialize.


  Add the following parameter to [4m~/.zshrc[24m for extra diagnostics on error:


    [1mGITSTATUS_LOG_LEVEL=DEBUG[0m

  Restart Zsh to retry gitstatus initialization:

    [32m[4mexec[24m[32m zsh[39m

"(anon):setopt:7: can't change option: monitor\n\n[\u001b[31mERROR\u001b[39m]: gitstatus failed to initialize.\n\n\n  Add the following parameter to \u001b[4m~/.zshrc\u001b[24m for extra diagnostics on error:\n\n    \u001b[1mGITSTATUS_LOG_LEVEL=DEBUG\u001b[0m\n\n  Restart Zsh to retry gitstatus initialization:\n\n    \u001b[32m\u001b[4mexec\u001b[24m\u001b[32m zsh\u001b[39m\n"
["\u001b]1337;RemoteHost=miharekar@iMac-Pro.local\u0007\u001b]1337;CurrentDir=/Users/miharekar/Development/personal/rdbg\u0007\u001b]1337;ShellIntegrationVersion=6;shell=zsh\u0007/var/folders/x1/h2b59yq14cs6pv9r_x1_39lw0000gn/T/ruby-debug-sock-501/ruby-debug-miharekar-12243"]
[Start session]
{"d":{},"f":"25fb05b7-d293-4b74-94c7-2552b5508466","g":"rdbg","h":"Attach with rdbg","i":{"uri":{"$mid":1,"fsPath":"/Users/miharekar/Development/personal/rdbg","external":"file:///Users/miharekar/Development/personal/rdbg","path":"/Users/miharekar/Development/personal/rdbg","scheme":"file"},"name":"rdbg","index":0},"j":{"type":"rdbg","name":"Attach with rdbg","request":"attach","__configurationTarget":6,"rdbgExtensions":["traceInspector"],"rdbgInitialScripts":[]}}
```

Feels like it's related to the theme I metioned above.

Reading [this issue](https://github.com/romkatv/gitstatus/issues/267) it might be that the terminal is invoked in an interactive way, instead of a non-interactive one? I wonder why it works on 0.1.0 and previous versions 🤔

**Comment by plfoley** [comment] 2023-06-05 13:09
@ono-max Attaching using rdbg in command line works fine for both the test script and Rails.

@st0012 Setting the Ruby Version Manager (rbenv in my case) causes the attach to run in an infinite loop. I have to kill the VSCode window to be able to attach again.

What @miharekar said rang a bell tough. I saw [commit](https://github.com/ruby/vscode-rdbg/commit/7e5eeb475efa4b7975bba39a8535374fcc611d73) when trying to figure out the issue in the beginning. There seems to be some issue specific to zsh regarding loading the environment configuration when using rbenv. It mentions the interactive shell...

I went in the extention.js:311 file and removed the 'i' option on the shell invocation. My debugger attaches fine now with version 0.2.1 and I am able to hit breakpoints.

**Comment by plfoley** [comment] 2023-06-07 22:18
@ono-max I think I found the root cause of the issue. There seems to be a conflict with the decoration happening when loading iTerm2 shell integrations.

You can prevent that from happening by setting TERM=dumb which should not cause side-effects for your extension.

Here is the code I used to test:
```
	makeShellCommand(cmd: string) {
		const shell = process.env.SHELL;
		if (this.needShell(shell)) {
			const interactiveShellCommand = shell + " -lic '" + cmd + "'"
			if (shell.endsWith("zsh")) {
				return "export TERM=dumb; " + interactiveShellCommand;
			}
			else{
				return interactiveShellCommand;
			}
		} else {
			return cmd;
		}
	}
```

With this change you can still load ~/.zshrc thus keeping support for rbenv and fix the attach issue.

It would be great if someone who has the same issue would be able to test this locally by replacing the `makeShellCommand` function  in the file `/Users/<username>/.vscode/extensions/koichisasada.vscode-rdbg-0.2.1/out/extension.js` with the code above and trying to attach.

@ono-max You can reproduce this by installing the iTerm2 Shell Integration and setting your login shell to zsh.
I can create a PR if you give me push rights or you can reintegrate the change yourself as you see fit.

**Comment by ono-max** [comment] 2023-06-08 00:13
Thank you, @plfoley ! I try to find another approach to fix this problem. However, your solution is the best. Also, I was able to reproduce this problem in your way, and it fixes the problem!

@plfoley Could you create the PR? I'll merge it!

**Comment by plfoley** [comment] 2023-06-08 02:29
All yours! Happy to see this fixed.
One thing you could do to improve on my solution would be to test if the file ~/.iterm2_shell_integration.zsh exists.
That would be a a sure-fire way of telling if iTerm2 Shell Integration was deployed but that would increase the coupling with their implementation a bit as well.
It is your call at this point.

**Comment by plfoley** [comment] 2023-06-08 11:39
@miharekar You would need to reload the extension after you change the code for the changes to take effect. The easiest way of doing this would be to kill and re-open your VSCode window.

The solution you have will indeed work instantaneously as every time you attach, you spawn a new shell and ~/.zshrc get re-evaluated.

Actually the fix you implemented is how I figured out that the issue was with iTerm2 Shell Integrations in the first place. The problem with that solution is that it requires a manual operation on every system. Be also mindful that if you reinstall iTerm2 Shell Extension later, the problem might reappear when changing the content of ~./zshrc.

**Comment by miharekar** [comment] 2023-06-08 12:35
@plfoley it does not. I saw there's quite a diff between [what I have](https://gist.github.com/miharekar/40593f6f7fd60b3a175f395372d2ae78) and [what's on their website](https://iterm2.com/shell_integration/zsh).

Going to be updating… 😅

**Comment by plfoley** [comment] 2023-06-08 12:40
@miharekar @ono-max This is what I feared tough. This means we have a weak point with the proposed fix as it won't cover old versions of shell integration scripts. 

I think this might require a note in the ReadMe.

**Comment by ono-max** [comment] 2023-06-08 13:31
Oh, I see. So the current approach is a partial solution.

**Comment by plfoley** [comment] 2023-06-08 14:34
It will work for all Shell Integration scripts that were installed after they added the test for `TERM=dumb` but not for those that were installed before that.

I checked and this condition has been there since at least December 2019 in their code base. The history stops there as the file was maybe moved, but this condition might have been there even before that.

**Comment by ono-max** [comment] 2023-06-09 10:47
@miharekar 

> So instead of relying on interactive terminal to load them, you'd try to load them in the way they should be loaded from their respective readmes

You mean, we should run the following command instead of loading shell?

```sh
eval "$(~/.rbenv/bin/rbenv init - bash)"
```

**Comment by miharekar** [comment] 2023-06-09 11:26
I meant the eval. Loading zshrc will have the same issue as we have right now, no?

**Comment by plfoley** [comment] 2023-06-09 11:41
@miharekar is correct: If you load the content of `~/.zshrc` you will also load iTerm2 Shell Integration scripts.
What could cause issues would be if rbenv requires something else from the `~/.zshrc` to be loaded beforehand.

I am not quite sure to understand why rbenv decided to put its configuration in `~/.zshrc` instead of `~/.zshenv`.
Clarifying these reasons might give you a better shot at fixing this issue long term.
But I agree with @miharekar and what was said in the Oh My Zsh issue, I don't see why it should require be run in either a login or interactive shell. Since I am new to Ruby, I may lack background information on the matter.

**Comment by ono-max** [comment] 2023-06-09 12:40
I see. Thanks, guys. I'm not sure about the background of rbenv. Thus, I asked the question.

**Comment by ono-max** [comment] 2023-06-13 02:32
I noticed that the version managers for Python and Nodejs use .zshrc. Using .zshrc to load initial commands may be a well-known way.

https://github.com/pyenv/pyenv#set-up-your-shell-environment-for-pyenv
https://github.com/nodenv/nodenv#basic-github-checkout
https://github.com/nvm-sh/nvm#deeper-shell-integration

**Comment by plfoley** [comment] 2023-06-13 16:40
What you say is true, but they mention this just after the ./zshrc setup in the pyenv documentation:

```If you wish to get Pyenv in noninteractive login shells as well, also add the commands to ~/.zprofile or ~/.zlogin.```

What I don't understand is why they don't suggest putting this in the config file that is common to all shells. They might have some reason for doing so.

**Comment by rnystrom** [comment] 2023-06-22 01:00
I'm also using zsh + chruby and having issues. Either:

1. I set `rubyVersionManager` to `chruby` and it infinitely spins
2. I set `rubyVersionManager` to `none` and the debugger crashes on launch with `check_for_activated_spec` (which makes sense as I believe its not using `chruby`)

I expect option 1 is what I should be doing, but I'm confused about the infinite loop. I've had issues before with our setup (chruby + VS Code + rdbg + Ruby LSP) and have the following in both my `.zshrc` and `.zprofile`.

```sh
# brew
eval "$(/opt/homebrew/bin/brew shellenv)"
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
export PATH="$HOME/.bin:$PATH"

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# chruby
source $(brew --prefix)/opt/chruby/share/chruby/chruby.sh
source $(brew --prefix)/opt/chruby/share/chruby/auto.sh
chruby_auto
```

When I remove the `chruby` bits from `.zprofile` I get:

```
Error: Failed to activate Ruby environment using chruby. Error: Error: Command failed: /bin/zsh -lic 'chruby-exec "3.1.2" -- ruby' -rjson -e "printf(%{RUBY_ENV_ACTIVATE%sRUBY_ENV_ACTIVATE}, JSON.dump(ENV.to_h))"
```

Which makes sense.

Any tips for debugging and/or working around the infinite spinner?

**Comment by plfoley** [comment] 2023-06-24 21:45
@rnystrom I encounter the same issue with rbenv. My solution is not to specify the environment manager in the rdbg plugin at all.

In the previous version, I managed to get the debugger to attach by specifying the path of rdbg through the shim in the launch.json tasks like this:
E.G.: "rdbgPath": "~/.rbenv/shims/rdbg"

As of the latest version with the local patch discussed here applied, I don't need to do this anymore however. It might have to do with how I load rbenv in the zsh configurations files. (I did moved it to the global zsh config file)

Sorry I can't be more specific, I am really not familiar with chruby, but at least you have a lead to explore...

**Comment by rnystrom** [comment] 2023-06-26 18:56
Ya selecting `none` at least doesn't hang up the debugger, but it doesn't debug either (`check_for_activated_spec` crash).

**Comment by bjaglin-swile** [comment] 2023-07-20 21:24
It looks like we have 2 separate issues being discussed here
1. the original one from the [description](https://github.com/ruby/vscode-rdbg/issues/277#issue-1738822369), which is a hard failure, independent of the usage of a version manager or not, and likely related to the iterm2 integration
1. a [more recent one](https://github.com/ruby/vscode-rdbg/issues/277#issuecomment-1601872685), which is a hang/freeze due to the usage of a version manager, without a lead on the root cause at the moment but discussed in https://github.com/ruby/vscode-rdbg/issues/295

**Comment by andretf** [comment] 2023-10-18 04:47
@miharekar solution worked for me slightly changing to `-z "$VSCODE"`. Although Output still have some errors:

```
tput: No value for $TERM and no -T specified

(anon):setopt:7: can't change option: monitor


[[31mERROR[39m]: gitstatus failed to initialize.


  Add the following parameter to ~/.zshrc for extra diagnostics on error:

    GITSTATUS_LOG_LEVEL=DEBUG

  Restart Zsh to retry gitstatus initialization:

    [32mexec zsh[39m

"tput: No value for $TERM and no -T specified\n(anon):setopt:7: can't change option: monitor\n\n[\u001b[31mERROR\u001b[39m]: gitstatus failed to initialize.\n\n\n  Add the following parameter to ~/.zshrc for extra diagnostics on error:\n\n    GITSTATUS_LOG_LEVEL=DEBUG\n\n  Restart Zsh to retry gitstatus initialization:\n\n    \u001b[32mexec zsh\u001b[39m\n"
[]
[Start session]
```

**Comment by ono-max** [comment] 2023-10-22 10:10
I apologize for any inconvenience, everyone. I will be discussing a solution to address these issues with the original author. Please bear with us a moment.

**Comment by natesalisbury** [comment] 2023-12-06 04:12
I'm seeing this same issue but I'm using bash. 

<img width="270" alt="image" src="https://github.com/ruby/vscode-rdbg/assets/1263438/0ab13131-d5f9-46b8-9a24-4d0dbb174440">

Setting the Ruby Version Manager to rbenv also gives me an infinite loop like others have reported.

**Comment by plfoley** [comment] 2023-12-21 01:38
Hi guys,
I have found a probably better way to fix this problem without having to touch the code of the extension or have to tell people to put their rbenv initialization routine in the login shell configuration file.

Wrap your shell integration initialization in the following condition:
```
if [[ "$TERM_PROGRAM" == "vscode" ]]; then
  test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
fi
```

This will prevent the shell integration from being loaded when the parent process is VSCode.
This should probably also work with Oh My Zsh.

I encountered the same problem while playing with the TypeProf extension, so my guess is that this will be a very common occurence in the Ruby world.

I suggest you put something about this somewhere in the extension documentation so people can solve this easily.

HTH

**Comment by ono-max** [comment] 2023-12-25 10:05
Hello there, 

Apologies for the delay in response, Following a through discussion, we have determined that addressing this issue involves resolving the version manager. Consequently, if you encounter the problem, we recommend utilizing the version manager as a solution. The latest version of our extension now incorporates an updated version manager, ensuring seamless functionality without any issues.

We appreciate your patience throughout this process. Should you have  any further inquiries, please do not hesitate to reach out. Thank you.

I would like to express special appreciation to @plfoley for his dedicated efforts in assisting with this issue.

**Closed by ono-max** 2023-12-25 10:05 UTC
Labels: bug

**Comment by drewlustro** [comment] 2024-02-13 01:04
For anyone finding this thread, the issue for me was `fzf`.

A good way to avoid this problem is to define a special environment variable in `launch.json`:

```sh
"env": {
  "TERM_PROGRAM": "vscode",
}
```

Then, in `.zshrc` skip initialization of plugins that invoke `zle`
