### ISSUE TITLE
Break event does not displayed on GUI with specific environment

### ISSUE THREAD

**Issue by jljse** [ruby/vscode-rdbg#16] opened 2021-12-27 15:46 UTC
## Environment
- Windows11 WSL2: ubuntu 20.04.1
- ruby: 3.1.0p0 (in rbenv in wsl2)
- debug gem: 1.4.0 (globaly installed)
- vscode: 1.63.2
- vscode Remote - WSL: v0.63.13
- vscode rdbg ruby debugger: v0.0.8

## What happened
I'm not sure that this is vscode-rdbg's bug at all,
but breakpoint hit does not displayed on vscode on specific situation.

## Reproduce
1. Make foo.rb
```
while s = gets
  puts s
end
```

2. from Windows Terminal, open remote debug with
`$ rdbg -nO foo.rb`

3. From vscode, attach to process with default setting (generated by vscode-rdbg).
4. (breaks on gets line, press F5 twice)   (this is also weird, but that's not my point)
5. From vscode, set breakpoint on puts line.
6. MAXIMIZE vscode's window and Windows Terminal 's window.
7. Activate Windows Terminal and type something + RET into stdin.
8. Wait 1s
9. Alt+Tab to switch to vscode
10. (breakpoint-hit is not displayed, and GUI hungs)
11. Back to Windows Terminal and show vscode again, then breakpoint-hit is displayed.

**Comment by ko1** [comment] 2021-12-28 06:34
Sorry I couldn't reproduce it. It seems VSCode issue?
(my env: WSL2 + VSCode on windows host + putty, ruby 2.7.3p183 and debug.gem master)

**Comment by jljse** [comment] 2021-12-28 13:34
Yes, today I found below
microsoft/vscode#123257
This looks very same issue.
Sorry to bother you.

(FYI, WSL2 + vscode on windows (Remote SSH) + putty(ssh) makes same issue on my environment)

**Comment by ko1** [comment] 2021-12-28 15:23
Thank you. I close it and please reopen if we can help.

**Closed by ko1** 2021-12-28 15:23 UTC
